package main

import (
	"net/http"
	"strconv"
	"time"

	"github.com/prometheus/client_golang/prometheus"
	"github.com/prometheus/client_golang/prometheus/collectors"
	"github.com/prometheus/client_golang/prometheus/promhttp"
)

// requestDurationName is the series Micrometer publishes for
// management.metrics http.server.requests. Keeping the name and the label set
// is what lets the existing p50/p95/p99 panels keep working across the cutover
// instead of going blank the moment traffic moves.
const requestDurationName = "http_server_requests_seconds"

// unmatchedURI keeps a request that matched no route out of the label values,
// so a scanner cannot open a time series per path it probes.
const unmatchedURI = "UNKNOWN"

// Metrics owns its own registry rather than the default one, so two servers in
// one process — which every test binary has — cannot collide on registration.
type Metrics struct {
	registry *prometheus.Registry
	duration *prometheus.HistogramVec
}

func NewMetrics() *Metrics {
	registry := prometheus.NewRegistry()
	duration := prometheus.NewHistogramVec(prometheus.HistogramOpts{
		Name: requestDurationName,
		Help: "Duration of HTTP server requests, by route pattern.",
		// Explicit edges, because the JVM's histogram is generated by
		// Micrometer from its own percentile configuration and cannot be
		// reproduced edge for edge. The quantile a dashboard interpolates is
		// therefore close rather than identical across the cutover, which is
		// worth saying out loud rather than discovering in a comparison.
		Buckets: []float64{0.001, 0.005, 0.01, 0.025, 0.05, 0.1, 0.25, 0.5, 1, 2.5, 5, 10},
	}, []string{"method", "uri", "status", "outcome"})

	registry.MustRegister(duration)
	registry.MustRegister(collectors.NewGoCollector())
	registry.MustRegister(collectors.NewProcessCollector(collectors.ProcessCollectorOpts{}))
	return &Metrics{registry: registry, duration: duration}
}

// Handler serves the scrape endpoint.
func (m *Metrics) Handler() http.Handler {
	return promhttp.HandlerFor(m.registry, promhttp.HandlerOpts{})
}

// Middleware times every request, labelling it by the pattern the router
// matched rather than by the path, so ids do not become label values.
func (m *Metrics) Middleware(router *Router, next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		uri := unmatchedURI
		if pattern, matched := router.Match(r); matched {
			uri = pattern
		}
		recorder := &statusRecorder{ResponseWriter: w, status: http.StatusOK}
		start := time.Now()

		next.ServeHTTP(recorder, r)

		m.duration.WithLabelValues(
			r.Method, uri, strconv.Itoa(recorder.status), outcomeOf(recorder.status),
		).Observe(time.Since(start).Seconds())
	})
}

// outcomeOf reproduces Micrometer's outcome tag, so a query written against the
// JVM's series keeps selecting the same requests.
func outcomeOf(status int) string {
	switch {
	case status < 200:
		return "INFORMATIONAL"
	case status < 300:
		return "SUCCESS"
	case status < 400:
		return "REDIRECTION"
	case status < 500:
		return "CLIENT_ERROR"
	default:
		return "SERVER_ERROR"
	}
}

// statusRecorder observes the status a handler sets. It deliberately does not
// wrap Write: a handler that writes a body without setting a status leaves the
// zero value below, which is initialised to 200 — the status the standard
// library would send for it anyway. Wrapping Write would put a second copy of
// every response body on a path that has no reason to see one.
type statusRecorder struct {
	http.ResponseWriter
	status  int
	written bool
}

func (s *statusRecorder) WriteHeader(status int) {
	if !s.written {
		s.status = status
		s.written = true
	}
	s.ResponseWriter.WriteHeader(status)
}
